// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AppFooter: typeof import('./src/components/app-footer.vue')['default']
    AppHeader: typeof import('./src/components/app-header.vue')['default']
    AppHeaderCart: typeof import('./src/components/app-header-cart.vue')['default']
    AppHeaderNav: typeof import('./src/components/app-header-nav.vue')['default']
    AppHeaderSticky: typeof import('./src/components/app-header-sticky.vue')['default']
    AppMemberAside: typeof import('./src/components/app-member-aside.vue')['default']
    AppNavbar: typeof import('./src/components/app-navbar.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    XtxBread: typeof import('./src/components/library/xtx-bread.vue')['default']
    XtxBreadItem: typeof import('./src/components/library/xtx-bread-item.vue')['default']
    XtxButton: typeof import('./src/components/library/xtx-button.vue')['default']
    XtxCarousel: typeof import('./src/components/library/xtx-carousel.vue')['default']
    XtxCheckbox: typeof import('./src/components/library/xtx-checkbox.vue')['default']
    XtxCity: typeof import('./src/components/library/xtx-city.vue')['default']
    XtxConfirm: typeof import('./src/components/library/xtx-confirm.vue')['default']
    XtxDialog: typeof import('./src/components/library/xtx-dialog.vue')['default']
    XtxInfiniteLoading: typeof import('./src/components/library/xtx-infinite-loading.vue')['default']
    XtxMessage: typeof import('./src/components/library/xtx-message.vue')['default']
    XtxMore: typeof import('./src/components/library/xtx-more.vue')['default']
    XtxNumbox: typeof import('./src/components/library/xtx-numbox.vue')['default']
    XtxPagination: typeof import('./src/components/library/xtx-pagination.vue')['default']
    XtxSkeleton: typeof import('./src/components/library/xtx-skeleton.vue')['default']
    XtxSteps: typeof import('./src/components/library/xtx-steps.vue')['default']
    XtxStepsItem: typeof import('./src/components/library/xtx-steps-item.vue')['default']
    XtxTabs: typeof import('./src/components/library/xtx-tabs.vue')['default']
    XtxTabsPanel: typeof import('./src/components/library/xtx-tabs-panel.vue')['default']
  }
}
